version: "3.8"
services:
    postgres:
        image: postgres:13-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: overflowbot
            POSTGRES_PASSWORD: overflowbot
            POSTGRES_DB: overflowbot
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - pgdata
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8000:8080

volumes:
    pgdata:
