version: "3.8"
services:
        postgres:
                image: postgres:13-alpine
                restart: unless-stopped
                environment:
                        POSTGRES_USER: overflowbot
                        POSTGRES_PASSWORD: overflowbot
                        POSTGRES_DB: overflowbot
                        PGDATA: /var/lib/postgresql/data/pgdata
                volumes:
                        - ./database:/var/lib/postgresql/data/pgdata

        bot:
                image: oxodao/overflowbot:latest
                restart: unless-stopped
                volumes:
                        - ./sounds:/app/sounds
                        - ./config.json:/app/config.json
                ports:
                        - 8249:8249


        adminer:
                image: adminer
                restart: always
                ports:
                        - 8000:8080
