name: ci

on:
  create:
    tags:
      - '*'

jobs:
  multi:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract Git Tag
        id: extract-git-tag
        run: echo GIT_TAG=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
        
      -
        name: Building docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: oxodao/overflowbot:${{ env.GIT_TAG }}
        
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
